@startuml react component

object CreateGroup {
  state groupName: string
  state isValidate: boolean
}
object AddMembers {
  state members: string[]
  state isValidate: boolean
}
object ExpenseMain {
  groupName: string
  members: string[]
}

object CenteredOverlayForm {
  props title: string
  props inputType: string
  props onSumit: function

  state value: string
}

object CentertedOverlay


object AddExpenseForm {
  members: string[]
  ---
  state isCalender: boolean
  --- 
  state payer: string
  state description: string
  state price: number
  state date: Date
}

object ExpenseSummary {
  expenses: ExpenseInfo[]
  members: string[]
}

object ExpenseChart {
  props total: number
  props data: ExpensePart[]
}


object ExpenseList {
  list: ExpenseInfo[]
}

object ExpenseItem {
  data: ExpenseInfo
}

object CalenderInput {
  props value: Date
  props onChange: (value: Date) => void
}

CenteredOverlayForm *-- CentertedOverlay
CreateGroup *-- CenteredOverlayForm
AddMembers *-- CenteredOverlayForm

ExpenseMain *-- AddExpenseForm
AddExpenseForm *-- CalenderInput

ExpenseMain *-- ExpenseSummary
ExpenseSummary *-- ExpenseChart

ExpenseMain *-- ExpenseList
CentertedOverlay *-- ExpenseList
ExpenseList *-- ExpenseItem

@enduml